version: '3.8'

services:
  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:80

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - REQUEST_ORIGIN=http://localhost:80
    depends_on:
      - redis

  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data

